# docker-compose.yml
version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped 

volumes:
  sqlserver_data: