definitions:
  models.League:
    properties:
      current_week:
        type: integer
      matches:
        items:
          $ref: '#/definitions/models.Match'
        type: array
      teams:
        items:
          $ref: '#/definitions/models.Team'
        type: array
    type: object
  models.Match:
    properties:
      away_goals:
        type: integer
      away_team_id:
        type: integer
      home_goals:
        type: integer
      home_team_id:
        type: integer
      id:
        type: integer
      played:
        description: Maç oynandı mı?
        type: boolean
      week:
        description: Maçın oynandığı hafta
        type: integer
    type: object
  models.Team:
    properties:
      goals_against:
        description: Yediği goller
        type: integer
      goals_for:
        description: Attığı goller
        type: integer
      id:
        type: integer
      matches_played:
        description: Oynadığı maç sayısı
        type: integer
      name:
        type: string
      points:
        description: Puan
        type: integer
      strength:
        description: Takım gücü (1-100)
        type: integer
    type: object
info:
  contact: {}
paths:
  /league-table:
    get:
      description: Mevcut lig tablosunu puan sırasına göre döndürür
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.League'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Lig tablosunu getirir
      tags:
      - league
  /play-week:
    post:
      description: Belirtilen hafta için maçları simüle eder ve ligi günceller
      parameters:
      - description: Hafta numarası
        in: query
        name: week
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: Week played successfully
          schema:
            type: string
        "400":
          description: Invalid week parameter
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Belirli bir haftayı oynatır
      tags:
      - league
  /reset-league:
    post:
      description: Tüm takımları ve maçları sıfırlayarak ligi yeniden başlatır
      produces:
      - text/plain
      responses:
        "200":
          description: League reset successfully
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Ligi sıfırlar
      tags:
      - league
swagger: "2.0"
