definitions:
  models.League:
    properties:
      current_week:
        type: integer
      matches:
        items:
          $ref: '#/definitions/models.Match'
        type: array
      teams:
        items:
          $ref: '#/definitions/models.Team'
        type: array
    type: object
  models.Match:
    properties:
      away_goals:
        type: integer
      away_team_id:
        type: integer
      home_goals:
        type: integer
      home_team_id:
        type: integer
      id:
        type: integer
      played:
        type: boolean
      week:
        type: integer
    type: object
  models.Team:
    properties:
      draws:
        description: Yeni eklendi
        type: integer
      goals_against:
        type: integer
      goals_for:
        type: integer
      id:
        type: integer
      loses:
        description: Yeni eklendi
        type: integer
      matches_played:
        type: integer
      name:
        type: string
      points:
        type: integer
      strength:
        type: integer
      wins:
        description: Yeni eklendi
        type: integer
    type: object
info:
  contact: {}
paths:
  /fixture:
    get:
      description: Ligin tüm maç fikstürünü döndürür
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.League'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Tüm maç fikstürünü getirir
      tags:
      - league
  /league-table:
    get:
      description: Mevcut lig tablosunu puan sırasına göre döndürür
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.League'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Lig tablosunu getirir
      tags:
      - league
  /play-week:
    post:
      description: Ligin güncel haftasını simüle eder ve ligi günceller
      produces:
      - text/plain
      responses:
        "200":
          description: Week played successfully
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Mevcut haftayı oynatır
      tags:
      - league
  /reset-league:
    post:
      description: Tüm takımları ve maçları sıfırlayarak ligi yeniden başlatır
      produces:
      - text/plain
      responses:
        "200":
          description: League reset successfully
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Ligi sıfırlar
      tags:
      - league
  /simulate-all-weeks:
    post:
      description: Ligdeki kalan tüm haftaları otomatik olarak simüle eder ve sonuçları
        döndürür
      produces:
      - application/json
      responses:
        "200":
          description: Tüm simüle edilmiş maçların sonuçları
          schema:
            items:
              $ref: '#/definitions/models.Match'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Tüm ligi simüle eder
      tags:
      - league
swagger: "2.0"
